### PR TITLE
TLC-94: Use standard deviations instead of percentiles for BMI Status…

### PR DESCRIPTION
**Pull request by ouiliam**
…/growth chart, growth chart in BMI

	modified:   configuration/openmrs/apps/clinical/dashboard.json
	modified:   configuration/openmrs/apps/clinical/growthChartReference.csv
	new file:   configuration/openmrs/obscalculator/BMI_chart_SD.csv
	modified:   configuration/openmrs/obscalculator/BahmniObsValueCalculator.groovy

### CODE REVIEW

**Comment by rbuisson** [comment]
@ouiliam thanks for the PR.
We should also think about updating Bahmni Connect configuration files correct?

**Comment by ouiliam** [comment]
correct, we can't make a script to copy them?

**Comment by rbuisson** [comment]
No we can't really make a script because some files are not identical. For instance, some widgets on the dashboard had to be disabled so we can't simply copy extension.json for instance.
Same applies on home/app.json where some apps in the Home screen had to be disabled on Connect.

**Comment by ouiliam** [comment]
I haven't got connect set up in docker to test it, having problems with laptop battery at moment

**Comment by ouiliam** [comment]
maybe when we go through my docker checkup can set it up. still problems with reports and orders on local

**Pull request merged**
